version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cristian
      POSTGRES_DB: guayas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: node_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgresdbguayas_user:tA3SbsmZrW6yyVV1a4am1DS5OyLkUaiU@dpg-cuvvj22j1k6c738ak3qg-a.oregon-postgres.render.com/postgresdbguayas

      NODE_ENV: production
    ports:
      - "4000:4000"
    volumes:
      - .:/app

volumes:
  pgdata:
